import assert from "node:assert/strict";
import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { chromium } from "playwright-core";
const executablePath = [process.env.CHROME_PATH, "C:/Program Files/Google/Chrome/Application/chrome.exe", "C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe"].filter(Boolean).find(existsSync);
if (!executablePath) throw new Error("Set CHROME_PATH to run the demo interaction checks.");
const base = process.env.DEMO_URL || "http://127.0.0.1:1422/";
const output = "artifacts/demo";
mkdirSync(output, { recursive: true });
const browser = await chromium.launch({ executablePath, headless: true, args: ["--mute-audio"] });
const errors = [], remoteRequests = [], checks = [];
const check = message => { checks.push(message); console.log("PASS " + message); };
try {
  const page = await browser.newPage({ viewport: { width: 1440, height: 1080 }, colorScheme: "dark" });
  page.setDefaultTimeout(12000);
  page.on("pageerror", e => errors.push(e.message));
  page.on("console", m => { if (m.type() === "error") errors.push(m.text()); });
  page.on("dialog", d => d.accept());
  page.on("request", request => {
    const url = request.url();
    if (/^https?:/.test(url) && new URL(url).origin !== new URL(base).origin) remoteRequests.push(url);
  });
  await page.goto(base, { waitUntil: "networkidle" });
  const frame = page.frameLocator("#launcher-frame");
  await frame.locator(".primary-action").waitFor();
  await frame.locator(".music-toggle[data-state=ready]").waitFor();
  assert.equal(await frame.locator(".music-toggle").getAttribute("aria-pressed"), "false");
  check("music off on entry; iframe ready");
  await page.screenshot({ path: `${output}/desktop-dark.png`, fullPage: true });
  const targetApps = {codex:'codex', doubao:'doubao', terminal:'terminal', vscode:'vscode', cursor:'cursor', grokbot:'grok', deepseek:'deepseek', zcode:'zcode'};
  for (const [target, app] of Object.entries(targetApps)) {
    await page.goto(new URL('/?app=' + app + '&theme=dark', base).href, {waitUntil:'networkidle'});
    await frame.locator('.launcher-stage[data-selected-target="' + target + '"]').waitFor();
    await frame.locator('.primary-action').click();
    await page.waitForURL(url => url.pathname === '/themes' && url.searchParams.get('app') === app);
    assert.equal(new URL(page.url()).searchParams.get('theme'), 'dark');
    const theme = page.frameLocator('.theme-viewport iframe');
    await theme.locator(app === 'codex' ? '.stage' : '.application').waitFor();
    if (app !== 'terminal') {
      await page.getByRole('button', {name:'☼ 日间', exact:true}).click();
      await page.waitForURL(url => url.searchParams.get('theme') === 'light');
    }
    await page.getByRole('button', {name:'原版参考', exact:true}).click();
    await page.waitForURL(url => url.searchParams.get('theme') === 'original');
    await page.getByRole('link', {name:'← 返回启动器', exact:true}).click();
    await frame.locator('.launcher-stage[data-selected-target="' + target + '"]').waitFor();
    await frame.locator('.secondary-action').click();
    await page.waitForURL(url => url.pathname === '/themes' && url.searchParams.get('app') === app && url.searchParams.get('theme') === 'original');
  }
  check('all eight launch / restore links open the matching demo and return to the selected app');
  await page.goto(new URL('/?app=vscode&theme=dark', base).href, {waitUntil:'networkidle'});
  await page.locator('#simulate-error').click();
  await frame.locator('.primary-action').click();
  await frame.locator('.runtime-chip').filter({hasText:'ERROR'}).waitFor();
  await frame.locator('.primary-action').click();
  await page.waitForURL(url => url.pathname === '/themes' && url.searchParams.get('app') === 'vscode');
  check('error feedback blocks navigation; retry enters the demo');
  await page.goto(base, {waitUntil:'networkidle'});
  const select = frame.locator('select');
  // Continue visual-only launcher checks without leaving the page.
  await frame.getByRole("button", { name: "隐藏目标应用列表", exact: true }).click();
  await frame.locator(".launcher-stage[data-selector-state=collapsed]").waitFor();
  assert.equal(await select.isDisabled(), true);
  await frame.getByRole("button", { name: "展开目标应用列表", exact: true }).click();
  await frame.locator(".launcher-stage[data-selector-state=expanded]").waitFor();
  checks.push("joint toggles, selector disabled while hidden");
  await frame.locator(".music-toggle").click();
  await frame.locator(".music-toggle[data-state=playing]").waitFor();
  await page.waitForTimeout(1400);
  await page.screenshot({ path: `${output}/music-playing.png`, fullPage: true });
  await frame.locator(".music-toggle").click();
  await frame.locator(".music-toggle[data-state=paused]").waitFor();
  checks.push("packaged music plays and pauses");
  await page.locator('[data-backdrop="day"]').click();
  await page.waitForTimeout(400);
  await page.screenshot({ path: `${output}/desktop-light.png`, fullPage: true });
  await frame.getByRole("button", { name: "最小化", exact: true }).click();
  await page.locator("#closed-panel").waitFor();
  await page.locator("#reopen").click();
  await frame.locator(".music-toggle[data-state=ready]").waitFor();
  await frame.getByRole("button", { name: "关闭", exact: true }).click();
  await page.locator("#closed-panel").waitFor();
  await page.locator("#restart").click();
  await frame.locator(".primary-action").waitFor();
  checks.push("minimize, close, reopen and reset unload audio");
  await page.setViewportSize({ width: 390, height: 844 });
  await page.waitForTimeout(600);
  const bounds = await page.locator("#launcher-fit").boundingBox();
  assert.ok(bounds.x >= 0 && bounds.x + bounds.width <= 391);
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  await page.screenshot({ path: `${output}/mobile.png`, fullPage: true });
  checks.push("390px mobile layout fits without horizontal overflow");
  await page.emulateMedia({ reducedMotion: "reduce" });
  await frame.locator(".music-toggle").click();
  await frame.locator(".music-toggle[data-state=playing]").waitFor();
  await frame.locator(".music-toggle").click();
  checks.push("reduced-motion music toggle remains usable");
  assert.deepEqual(remoteRequests, [], "demo must not call third-party or local-app endpoints");
  assert.deepEqual(errors, [], "browser errors");
  writeFileSync(`${output}/report.json`, JSON.stringify({ base, checks, errors, remoteRequests }, null, 2));
  console.log(JSON.stringify({ passed: checks.length, checks, errors, remoteRequests }, null, 2));
} finally { await browser.close(); }
