import assert from "node:assert/strict";
import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { chromium } from "playwright-core";
const executablePath = [process.env.CHROME_PATH, "C:/Program Files/Google/Chrome/Application/chrome.exe", "C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe"].filter(Boolean).find(existsSync);
if (!executablePath) throw new Error("Set CHROME_PATH to run the demo interaction checks.");
const base = process.env.DEMO_URL || "http://127.0.0.1:1422/";
const output = "artifacts/demo";
mkdirSync(output, { recursive: true });
const browser = await chromium.launch({ executablePath, headless: true, args: ["--mute-audio"] });
const errors = [], remoteRequests = [], checks = [];
const check = message => { checks.push(message); console.log("PASS " + message); };
try {
  const page = await browser.newPage({ viewport: { width: 1440, height: 1080 }, colorScheme: "dark" });
  page.setDefaultTimeout(12000);
  page.on("pageerror", e => errors.push(e.message));
  page.on("console", m => { if (m.type() === "error") errors.push(m.text()); });
  page.on("dialog", d => d.accept());
  page.on("request", request => {
    const url = request.url();
    if (/^https?:/.test(url) && new URL(url).origin !== new URL(base).origin) remoteRequests.push(url);
  });
  await page.goto(base, { waitUntil: "networkidle" });
  const frame = page.frameLocator("#launcher-frame");
  await frame.locator(".primary-action").waitFor();
  await frame.locator(".music-toggle[data-state=ready]").waitFor();
  assert.equal(await frame.locator(".music-toggle").getAttribute("aria-pressed"), "false");
  check("music off on entry; iframe ready");
  await page.screenshot({ path: `${output}/desktop-dark.png`, fullPage: true });
  await frame.locator(".primary-action").click();
  await frame.locator(".runtime-chip").filter({ hasText: "MOUNTED" }).waitFor();
  assert.match(await frame.locator(".status-overlay p").innerText(), /模拟/);
  check("Codex mount is explicitly simulated");
  await frame.getByRole("button", { name: "日间", exact: true }).click();
  await frame.locator(".primary-action").click();
  await frame.locator(".runtime-chip").filter({ hasText: "WAITING" }).waitFor();
  await page.locator("#simulate-exit").click();
  await frame.locator(".runtime-chip").filter({ hasText: "MOUNTED" }).waitFor();
  check("day change waits for simulated exit, then resumes");
  await frame.locator(".secondary-action").click();
  await frame.locator(".runtime-chip").filter({ hasText: "WAITING" }).waitFor();
  await page.locator("#simulate-exit").click();
  await frame.locator(".status-overlay p").filter({ hasText: "原版入口" }).waitFor();
  check("native launch preserves exit-before-restart semantics");
  const select = frame.locator("select");
  for (const target of ["doubao", "terminal", "vscode", "cursor", "grokbot", "deepseek", "zcode", "codex"]) {
    await select.selectOption(target);
    await page.waitForTimeout(120);
    if (target === "grokbot") {
      assert.equal(await frame.locator(".primary-action").isDisabled(), true);
      assert.match(await page.locator("#target-note").innerText(), /不含/);
    } else if (target !== "codex") {
      await frame.locator(".primary-action").click();
      await page.waitForTimeout(1100);
      assert.match(await frame.locator(".status-overlay p").innerText(), /模拟/);
      if (["cursor", "vscode"].includes(target)) assert.equal(await frame.locator(".runtime-chip").innerText(), "COLOR");
    }
  }
  check("eight targets preserve public capability boundaries");
  await select.selectOption("vscode");
  await page.locator("#simulate-error").click();
  await frame.locator(".primary-action").click();
  await frame.locator(".runtime-chip").filter({ hasText: "ERROR" }).waitFor();
  await frame.locator(".primary-action").click();
  await frame.locator(".runtime-chip").filter({ hasText: "COLOR" }).waitFor();
  check("raw error display and retry recover");
  await frame.getByRole("button", { name: "隐藏目标应用列表", exact: true }).click();
  await frame.locator(".launcher-stage[data-selector-state=collapsed]").waitFor();
  assert.equal(await select.isDisabled(), true);
  await frame.getByRole("button", { name: "展开目标应用列表", exact: true }).click();
  await frame.locator(".launcher-stage[data-selector-state=expanded]").waitFor();
  checks.push("joint toggles, selector disabled while hidden");
  await frame.locator(".music-toggle").click();
  await frame.locator(".music-toggle[data-state=playing]").waitFor();
  await page.waitForTimeout(1400);
  await page.screenshot({ path: `${output}/music-playing.png`, fullPage: true });
  await frame.locator(".music-toggle").click();
  await frame.locator(".music-toggle[data-state=paused]").waitFor();
  checks.push("packaged music plays and pauses");
  await page.locator('[data-backdrop="day"]').click();
  await page.waitForTimeout(400);
  await page.screenshot({ path: `${output}/desktop-light.png`, fullPage: true });
  await frame.getByRole("button", { name: "最小化", exact: true }).click();
  await page.locator("#closed-panel").waitFor();
  await page.locator("#reopen").click();
  await frame.locator(".music-toggle[data-state=ready]").waitFor();
  await frame.getByRole("button", { name: "关闭", exact: true }).click();
  await page.locator("#closed-panel").waitFor();
  await page.locator("#restart").click();
  await frame.locator(".primary-action").waitFor();
  checks.push("minimize, close, reopen and reset unload audio");
  await page.setViewportSize({ width: 390, height: 844 });
  await page.waitForTimeout(600);
  const bounds = await page.locator("#launcher-fit").boundingBox();
  assert.ok(bounds.x >= 0 && bounds.x + bounds.width <= 391);
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  await page.screenshot({ path: `${output}/mobile.png`, fullPage: true });
  checks.push("390px mobile layout fits without horizontal overflow");
  await page.emulateMedia({ reducedMotion: "reduce" });
  await frame.locator(".music-toggle").click();
  await frame.locator(".music-toggle[data-state=playing]").waitFor();
  await frame.locator(".music-toggle").click();
  checks.push("reduced-motion music toggle remains usable");
  assert.deepEqual(remoteRequests, [], "demo must not call third-party or local-app endpoints");
  assert.deepEqual(errors, [], "browser errors");
  writeFileSync(`${output}/report.json`, JSON.stringify({ base, checks, errors, remoteRequests }, null, 2));
  console.log(JSON.stringify({ passed: checks.length, checks, errors, remoteRequests }, null, 2));
} finally { await browser.close(); }
