// Generated by scripts/sync-reviewed-runtimes.mjs; artwork uses the shared asset table.
pub const CURSOR_VERSION: &str = "reviewed-cursor-3.17.21-v3";
pub const CURSOR_FILES: &[(&str, &[u8])] = &[
    ("adapter.mjs", include_bytes!("../resources/theme-packs/cursor/runtime/adapter.mjs")),
    ("ASSET_LICENSES.md", include_bytes!("../resources/theme-packs/cursor/runtime/ASSET_LICENSES.md")),
    ("delivery-runtime.mjs", include_bytes!("../resources/theme-packs/cursor/runtime/delivery-runtime.mjs")),
    ("extension/package.json", include_bytes!("../resources/theme-packs/cursor/runtime/extension/package.json")),
    ("extension/themes/diana-day-color-theme.json", include_bytes!("../resources/theme-packs/cursor/runtime/extension/themes/diana-day-color-theme.json")),
    ("extension/themes/diana-night-color-theme.json", include_bytes!("../resources/theme-packs/cursor/runtime/extension/themes/diana-night-color-theme.json")),
    ("LICENSE", include_bytes!("../resources/theme-packs/cursor/runtime/LICENSE")),
    ("README-LOCAL.txt", include_bytes!("../resources/theme-packs/cursor/runtime/README-LOCAL.txt")),
    ("SECURITY.md", include_bytes!("../resources/theme-packs/cursor/runtime/SECURITY.md")),
    ("settings-jsonc.mjs", include_bytes!("../resources/theme-packs/cursor/runtime/settings-jsonc.mjs")),
    ("theme.css", include_bytes!("../resources/theme-packs/cursor/runtime/theme.css")),
    ("SHA256SUMS.txt", include_bytes!("../resources/theme-packs/cursor/runtime/SHA256SUMS.txt")),
];
pub const GROKBOT_VERSION: &str = "reviewed-grok-bot-0.28.0-v3";
pub const GROKBOT_FILES: &[(&str, &[u8])] = &[
    ("adapter.mjs", include_bytes!("../resources/theme-packs/grokbot/runtime/adapter.mjs")),
    ("ASSET_LICENSES.md", include_bytes!("../resources/theme-packs/grokbot/runtime/ASSET_LICENSES.md")),
    ("delivery-runtime.mjs", include_bytes!("../resources/theme-packs/grokbot/runtime/delivery-runtime.mjs")),
    ("LICENSE", include_bytes!("../resources/theme-packs/grokbot/runtime/LICENSE")),
    ("README-LOCAL.txt", include_bytes!("../resources/theme-packs/grokbot/runtime/README-LOCAL.txt")),
    ("SECURITY.md", include_bytes!("../resources/theme-packs/grokbot/runtime/SECURITY.md")),
    ("theme.css", include_bytes!("../resources/theme-packs/grokbot/runtime/theme.css")),
    ("SHA256SUMS.txt", include_bytes!("../resources/theme-packs/grokbot/runtime/SHA256SUMS.txt")),
];
